### ISSUE TITLE
Doesn't work on After Effects!

### ISSUE THREAD

**Issue by gersirami** [grefel/restix#2]
Hi!
Thank you for sharing your code. I tried it and works great with InDesign. Is there any way to make it work with After Effects?!
Thanks!

**Comment by grefel** [comment]
I do not know details about After Effects ExtendScript. This script needs to run command line actions via AppleScript/curl and VB-Script/MSXML2.ServerXMLHTTP.6.0 
In InDesign we have doScript() is there anything similar in AE?

**Comment by gersirami** [comment]
@grefel In AE there's no `app.doScript()` and according to this [answer](https://stackoverflow.com/questions/15074220/what-is-the-difference-between-app-doscript-and-evalfile/15097975#15097975) it can't be replaced with $.evalFile.
Thanks anyway!

**Comment by grefel** [comment]
IF doScript is not available i.e for AE there might be a chance via File.execute() 
https://www.indesignjs.de/extendscriptAPI/indesign-latest/#File.html#d1e6347__d1e6356 
Run a bash Script with teh curl command on Mac and a Bat on Windows with the vbs (https://stackoverflow.com/questions/11899730/running-vbscript-from-batch-file). Would need a bit of redesign, but could work... You probably need to read the result vie File.read()
