### ISSUE TITLE
Need to wrap the URL in encodeURI()

### ISSUE THREAD

**Issue by Id-Extras** [grefel/restix#3]
Great script, works in InDesign 2023 with HTTPS, so that's great.
Certain URLs have to be wrapped in an encodeURI command. For instance, if a URL contains quote marks (otherwise the VBScript won't compile, haven't tested on the Mac side).
Not sure whether the user should do that, or whether RESTIX should do it. But someone has to!
So either it should be included in the examples, or in the restix.jsx script itself.

Thanks!
Ariel

**Comment by grefel** [comment]
Thanks for looking at the code. The `encodeURI()` command was only processed in the mac/curl version. I moved it to the right place - `INNER.checkRequest()` Should work now.
