### ISSUE TITLE
Getting data from external JS library

### ISSUE THREAD

**Issue by fallenartist** [grefel/restix#5]
Hi, can restix be somehow used to receive data from [this library](https://github.com/commenthol/date-holidays)? It outputs [JSON](https://codepen.io/figle/pen/XWPaRPz?editors=0010) based on specific input? Thank you.

**Comment by grefel** [comment]
restix is meant to read any data provided via http(s). As far as I understand https://github.com/commenthol/date-holidays you don't need restix here. Simply read the JSON via eval() or JSON.parse().
