### ISSUE TITLE
All HTTP request fails with InDesign

### ISSUE THREAD

**Issue by shiv-allva** [grefel/restix#6]
When I run the connect.jsx in InDesign, all the HTTPs request fails except the image download. 
I tried InDesign versions: 2021, 2022, and 2023
Could you help me with this, please?

// Showing a resource  ----
Response HTTP Status: 404
Response Body: {}
// Creating a resource  ----
Response HTTP Status: 404
Response Body: {}
// Updating a resource PUT  ----
Response HTTP Status: 404
Response Body: {}
// Updating a resource PATCH  ----
Response HTTP Status: 404
Response Body: {}
// Deleting a resource  ----
Response HTTP Status: 404
Response Body: {}
// Filtering resources  ----
Response HTTP Status: 404
Response Body: {}
// Fetch a file  ----
Response HTTP Status: 200
Response Body: outFile
Image downloaded << WORKS

**Comment by grefel** [comment]
Server does not like a doubled // in the url. I fixed this recently introduced bug in 7f43766
