### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by Sab-tech-lab** [grefel/restix#7]
Is possible upload a file to server?

**Comment by grefel** [comment]
see the POST example here https://github.com/grefel/restix/blob/master/examples/connect.jsx

**Comment by Sab-tech-lab** [comment]
Thanks, i have see example but no file upload example is disponible

**Comment by grefel** [comment]
In http files are uploaded with POST

**Comment by Sab-tech-lab** [comment]
Yes correct the upload is done with the post but in the examples it is not shown how to pass the file to the "fetch" function, how should I build the request object to pass it the file to upload?

**Comment by Sab-tech-lab** [comment]
After several attempts at uploading I have with windows I created this upload script that also allows fields in post. I attach the file if you want to include it as a function.
Thanks for the support.
[uploadScript.txt](https://github.com/user-attachments/files/15903285/uploadScript.txt)
